### ISSUE TITLE
Crashing with my AppCompatActivity

### ISSUE THREAD

**Issue by BasanthVerma** [00ec454/Ask#16]
Hi, when i am using Ask Library in my App, it is crashing, please find the details below.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.beyondseek.ServicesAroundMe/com.vistrav.ask.AskActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.onPostCreate(AppCompatDelegateImplV7.java:167)
                                                                                   at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:98)
                                                                                   at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1188)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2398)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
The code in the onCreate of my Permissions Activity:

 ```
 Ask.on(PermissionAcitvity.this)
                .forPermissions(Manifest.permission.ACCESS_COARSE_LOCATION
                        , Manifest.permission.WRITE_EXTERNAL_STORAGE,Manifest.permission.CALL_PHONE,Manifest.permission.ACCESS_NETWORK_STATE,
                        Manifest.permission.ACCESS_WIFI_STATE, Manifest.permission.MANAGE_DOCUMENTS,
                        Manifest.permission.CALL_PHONE, Manifest.permission.READ_EXTERNAL_STORAGE,Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .withRationales("Location permission need for map to work properly",
                        "In order to save file you will need to grant storage permission").go(); 
```
This is the App Theme that i am using:

`    <style name="AppTheme" parent="Theme.AppCompat.DayNight.DarkActionBar">`

The compileSdkVersion is 24
And buildToolsVersion  is '23.0.3'
Please help.

**Comment by 00ec454** [comment]
@BasanthVerma Please check these two links if it can helps you
[link1](http://stackoverflow.com/questions/21814825/you-need-to-use-a-theme-appcompat-theme-or-descendant-with-this-activity)
[link2](http://stackoverflow.com/questions/28570785/material-design-support-below-lollipop-crashes)

**Comment by BasanthVerma** [comment]
@00ec454  Thank you. I was able to solve it using the solution from Link 2, looks like i should have added

android:theme="@style/AppTheme" under the <application> tag in my AndroidManifest.
