### ISSUE TITLE
Some time activity crashes ("Caused by: java.lang.NullPointerException at com.vistrav.ask.Ask.getAnnotation Method(Ask.java:197))

### ISSUE THREAD

**Issue by Shahjahan786** [00ec454/Ask#27]

**Comment by android-guilherme** [comment]
same here

**Comment by android-guilherme** [comment]
```
Ask.on(this)
                .forPermissions(Manifest.permission.ACCESS_COARSE_LOCATION)
                .withRationales("É necessário sua localização para o funcionamento do app")
                .id(PERMISSION_ID)
                .go();
```

```
FATAL EXCEPTION: main
                                                                                Process: br.com.minervaaplicativos.petcel, PID: 5091
                                                                                java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
                                                                                    at com.vistrav.ask.Ask.getAnnotatedMethod(Ask.java:201)
                                                                                    at com.vistrav.ask.Ask.go(Ask.java:115)
                                                                                    at br.com.minervaaplicativos.petcel.activities.base.main.MainMap.checkPermission(MainMap.java:234)
                                                                                    at br.com.minervaaplicativos.petcel.activities.base.main.MainMap.getUserLocation(MainMap.java:137)
                                                                                    at br.com.minervaaplicativos.petcel.activities.base.main.MainMap.onMapReady(MainMap.java:116)
                                                                                    at com.google.android.gms.maps.zzaj.zza(Unknown Source)
                                                                                    at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source)
                                                                                    at android.os.Binder.transact(Binder.java:392)
                                                                                    at gl.b(:com.google.android.gms.DynamiteModulesB@11509448:20)
                                                                                    at com.google.android.gms.maps.internal.bf.a(:com.google.android.gms.DynamiteModulesB@11509448:5)
                                                                                    at com.google.maps.api.android.lib6.impl.bc.run(:com.google.android.gms.DynamiteModulesB@11509448:5)
                                                                                    at android.os.Handler.handleCallback(Handler.java:815)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                    at android.os.Looper.loop(Looper.java:207)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by android-guilherme** [comment]
Solved using:


```
@AskGranted(Manifest.permission.ACCESS_COARSE_LOCATION)
    public void mapAccessGranted(int id) {
        Log.i("MAIN MAP", "MAP GRANTED");
        getUserLocation();
    }

    @AskDenied(Manifest.permission.ACCESS_COARSE_LOCATION)
    public void mapAccessDenied(int id) {
        Log.i("MAIN MAP", "MAP DENIED");
        checkPermission();
    }
```

**Comment by 00ec454** [comment]
oh cool. closing this issue now
